### ISSUE TITLE
compass missing?

### ISSUE THREAD

**Issue by hyanwong** [jpmschuler/docker-node-php#1]
On the docker hub page for this image, it say it contains compass, but that seems to be missing from the latest version?

**Comment by jpmschuler** [comment]
Thx, I updated the Docker Hub description to match the readme.
The last image version with compass was v3.6.0

That said, Ruby Sass is deprecated https://sass-lang.com/ruby-sass as well as compass itself https://github.com/Compass/compass

Thus we slimmed the current image from quite everything, because we try to do everything without "native" tools but rather using npm/composer packages. To replace Ruby Sass and Compass we use 

- the Sass Dart implementation https://www.npmjs.com/package/sass with
- Compass Mixins https://www.npmjs.com/package/@melonthierry/compass-mixins

and e.g.
`npx sass --update  --load-path=node_modules/@melonthierry/compass-mixins/lib  Stylesheets/my.scss`
to have compass functionality with the build speed of sass dart.

You can easily add your own images to docker hub by creating a free account and linking a public github repository like this and let docker hub do the rest. Thus you could copy a `Dockerfile` and adapt it to your personal needs.

**Comment by hyanwong** [comment]
Useful about the replacement packages. Thanks
